version: '3.9'

services:
  # Nginx service
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - "8200:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - net-shortUrl
  php:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: short
    volumes:
        - ./:/www
        - /www/vendor
        - /www/bootstrap/cache
    networks:
        - net-shortUrl
    expose:
    - "9003"
  # MySQL service
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     # MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     # MYSQL_USER: laravel
  #     MYSQL_PASSWORD: passed
  #   ports:
  #     - '3306:3306'
    # volumes:
    #   - mysql-data:/var/lib/mysql
    # networks:
    #   - net-shortUrl
networks:
  net-shortUrl:
    driver: bridge
